### PR TITLE
Bruce made an awesome change

### PR DESCRIPTION
**Pull request by BruceBray**

### CODE REVIEW

**Comment by PeterBell** [comment]
LGTM 👍

**Comment by mikepgit** [comment]
👍

**Comment by PeterBell** [comment]
Hey @BruceBray looks awesome - could you add any text to either of these files?

**Comment by CatherineNC** [comment]
LGTM

**Comment by PeterBell** [comment]
Hey @BruceBray I've got an idea - would you mind if *I* added some text to those files?

**Comment by BruceBray** [comment]
sure

**Comment by PeterBell** [comment]
👍

**Comment by PeterBell** [comment]
harry-potter-congrats

**Pull request merged**
