### PR TITLE
Fix user login bug

### PR DESCRIPTION
**Pull request by PeterBell**

### CODE REVIEW

**Comment by PeterBell** [comment]
This is designed to fix #4

**Comment by mikepgit** [comment]
Looks like a great fix!

**Comment by dabutz** [comment]
👍

**Comment by CatherineNC** [comment]
👍

**Comment by asbeckler** [comment]
LGTM 🉑

**Comment by BruceBray** [comment]
lgtm 👍

**Comment by ems53717** [comment]
Insufficient. Keep trying.

**Pull request merged**
